services:
  mysql:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shoppy_db
      - MYSQL_USER=nestuser
      - MYSQL_PASSWORD=nestpass
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
